name: complete_asana_authorization
description: A Dart Functions Framework microservice for exchanging a code returned from asana for credentials.
# version: 0.1.0
# homepage: https://www.example.com
publish_to: none

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:
  functions_framework: any
  shelf: any
  http: any
  json_serializable: ^4.0.0-nullsafety.0
  freezed_annotation: ^0.13.0-nullsafety.0
  googleapis_auth: any
  googleapis: any

dev_dependencies:
  build_runner: any
  build_verify: any
  functions_framework_builder:
    git:
      url: https://github.com/nickmeinhold/functions-framework-dart
      path: functions_framework_builder
      ref: no-sound-null-safety
  test: ^1.16.0-nullsafety.16
  test_process: any
  freezed: ^0.13.0-nullsafety.2
  pedantic: ^1.10.0-nullsafety.3
  quiver: any